name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: infrakit-io/repo-standards-kit/.github/workflows/go-ci.yml@v1
    permissions:
      contents: write
    with:
      coverage-badge: true
      coverage-threshold: 90
